### ISSUE TITLE
Error with jenkins

### ISSUE THREAD

**Issue by rourke750** [Civcraft/ItemExchange#13]
http://192.95.27.125:8080/view/Live/job/ItemExchange-master/62/console

**Comment by ttk2** [comment]
that looks like invalid source code, not jenkins.

**Comment by rourke750** [comment]
Its fine in my environment and isn't really different to the previous 1.8.3
so don't know what's different.

**Comment by WildWeazel** [comment]
Did you build with Eclipse or Maven? The issue seems to be the encoding specified in the pom.

**Comment by rourke750** [comment]
I normally build with eclipse but I just take my source and upload it to github if eclipse doesn't show any errors.
