### ISSUE TITLE
Depth strider 

### ISSUE THREAD

**Issue by hlprimm** [Civcraft/ItemExchange#14]
Depth strider has no abbreviation AFIAK

**Comment by ttk2** [comment]
well that's a problem for allowing chest trading for it right?

**Comment by hlprimm** [comment]
Yes. It currently reports as "null" so /ies does not allow addition or removal of it from the button, as "null" is not in the enchantments.csv

I created the pull to fix this (hopefully), here:

**Comment by ttk2** [comment]
this is just a config update right? I can grab the new one off github and put it up?

**Comment by Maxopoly** [comment]
Fixed with https://github.com/Civcraft/ItemExchange/pull/15/files, please close
