### ISSUE TITLE
Fix /iec

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/ItemExchange#19]
It should use the line of sight blocks instead of the last target blocks, the last target blocks are very unreliable.

**Comment by erocs** [comment]
Use the BlockIterator. https://github.com/Civcraft/Citadel/blob/1d0378ea5/src/vg/civcraft/mc/citadel/command/commands/Acid.java#L44

**Comment by Maxopoly** [comment]
I wanted to use that:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/LivingEntity.html#getLineOfSight(java.util.Set,%20int)
, but the BlockIterator looks a lot better, probably gonna use that, thanks.

**Comment by Maxopoly** [comment]
Fixed by https://github.com/Civcraft/ItemExchange/commit/b44080b76b3a3a881e44b7ef8181d70c5e685415

Tested and works @ttk2  @rourke750  could one of you stage this?

**Comment by ttk2** [comment]
staged.
