### ISSUE TITLE
Add logging of successful exchanges

### ISSUE THREAD

**Issue by GavJenks** [Civcraft/ItemExchange#9]
Pretty much what it says on the tin. Just name and date and which exchange.
Probably would need a server owner option for how long before culling logs.

Obviously, this is useful for adjusting your marketing based on what sort of people are buying from you, and being able to see how/when people buy things in groups -- it matters whether person A buys X and Y and person B buys W and Z, versus other unknown combinations. I may want to make sure I stock X and Y at the same time, versus haphazardly, if one group of people buys both.

You may also want to know which people are buying things for strategic purposes. Like keeping track of who is buying bastions or gunpowder. Since this is effectively supposed to be roleplaying an actual shopkeeper, there's no reason why you shouldn't be able to know who your customers are.

Also, what made me want this personally is for libraries -- I am currently resorting to hefty diamond security deposits using this mod for checking out books. But I would very much prefer to just simply know who checked it out and be able to use a library card... or just nothing/a piece of dirt/whatever. But I can't do that if I don't know who is using the itemexchange.

**Comment by ttk2** [comment]
Are the exchanges logged to JukeAlert?

**Comment by rourke750** [comment]
No they arent

**Comment by ttk2** [comment]
Then how are they logged.

**Comment by rourke750** [comment]
Player x interacted with chest at x y z

**Comment by erocs** [comment]
Maybe we should add an ItemExchange hook to JukeAlert and let a snitch take
care of it. That way we don't have to recreate the same logging mechanisms
which already exist in JA.

**Comment by ttk2** [comment]
I think that's the only good way to do this

**Comment by rourke750** [comment]
https://github.com/Civcraft/JukeAlert/commit/cb7fe0e42c75dccaba3060433aea374edbded398

http://imgur.com/LPPOiMK
